development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= "stagehand_staging#{ENV.fetch('STAGEHAND_TEST_DATABASE_SUFFIX', '')}" %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DB_PORT', '3306') %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= "stagehand_staging#{ENV.fetch('STAGEHAND_TEST_DATABASE_SUFFIX', '')}" %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DB_PORT', '3306') %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= "stagehand_production#{ENV.fetch('STAGEHAND_TEST_DATABASE_SUFFIX', '')}" %>
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DB_PORT', '3306') %>
